# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a7a86da0971689c23545e6c2110475ee3367589e7efb9c47d9127e2264c0ff7f2a7c1eb8186f62f6108a76994baa8f505cba3ba66daca6cc705034333ce3ba63

test:
  secret_key_base: 01026402c8bae4c767db6532c598d3e0fc88476554ea2ce0f728b5d17e5bd731fe2ff56da60e1c9a3f20e1f06b18ae80df335a9fb7cfd7c120155a8e1e3f81de

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
